//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spirit
    {
        public int Id { get; set; }
        public int AlcoholID { get; set; }
        public string Flavour { get; set; }
        public string Type { get; set; }
    
        public virtual Alcohol Alcohol { get; set; }
    }
}
